update+fix:
- fix log_collection_args which is causing error
- fix wrong resource name
- fix wrong timestamp format in README
- add more into README
- fix wrong env variable and use label instead of env variable

Signed-off-by: Wen Zhou <wenzhou@redhat.com>

diff --git a/collection-scripts/gather b/collection-scripts/gather
--- a/collection-scripts/gather
+++ b/collection-scripts/gather
@@ -1,14 +1,14 @@
 #!/bin/bash
-# shellcheck disable=SC2154,SC1091
+# shellcheck disable=SC2154,SC1091,SC2086
 source common.sh
 
 # for new flag to get since and since-time
 get_log_collection_args
 
 
-# generate /must-gather/version file
-echo "opendatahub/must-gather" > /must-gather/version
-version >> /must-gather/version
+# generate /must-gather/version file with RHOAI version
+echo "red-hat-data-services/must-gather" > /must-gather/version
+rhoai_version >> /must-gather/version
 
 # define default namespaces
 OPERATOR_NS=${OPERATOR_NAMESPACE:-redhat-ods-operator}
@@ -16,10 +16,10 @@ NOTEBOOKS_NS=${NOTEBOOK_NAMESPACE:-rhods-notebooks}
 MONITORING_NS=${MONITORING_NAMESPACE:-redhat-ods-monitoring}
 APPLICATIONS_NS=${APPLICATIONS_NAMESPACE:-redhat-ods-applications}
 
-oc adm inspect "${log_collection_args}" "namespace/$OPERATOR_NS" --dest-dir="$DST_DIR" || echo "Error getting logs from ${OPERATOR_NS}"
-oc adm inspect "${log_collection_args}" "namespace/$NOTEBOOKS_NS" --dest-dir="$DST_DIR" || echo "Error getting logs from ${NOTEBOOKS_NS}"
-oc adm inspect "${log_collection_args}" "namespace/$MONITORING_NS" --dest-dir="$DST_DIR"  || echo "Error getting logs from ${MONITORING_NS}"
-oc adm inspect "${log_collection_args}" "namespace/$APPLICATIONS_NS" --dest-dir="$DST_DIR"  || echo "Error getting logs from ${APPLICATIONS_NS}"
+oc adm inspect $log_collection_args "namespace/$OPERATOR_NS" --dest-dir="$DST_DIR" || echo "Error getting logs from ${OPERATOR_NS}"
+oc adm inspect $log_collection_args "namespace/$NOTEBOOKS_NS" --dest-dir="$DST_DIR" || echo "Error getting logs from ${NOTEBOOKS_NS}"
+oc adm inspect $log_collection_args "namespace/$MONITORING_NS" --dest-dir="$DST_DIR"  || echo "Error getting logs from ${MONITORING_NS}"
+oc adm inspect $log_collection_args "namespace/$APPLICATIONS_NS" --dest-dir="$DST_DIR"  || echo "Error getting logs from ${APPLICATIONS_NS}"
 
 # add DSCI and DSC
 get_operator_resource dscinitialization
