update:
- add support for DW components
- renaming for both kserve and modelmesh to use the same script
- add COMPONENT as flag
- move functions into common.sh

Signed-off-by: Wen Zhou <wenzhou@redhat.com>

diff --git a/collection-scripts/gather b/collection-scripts/gather
--- a/collection-scripts/gather
+++ b/collection-scripts/gather
@@ -1,24 +1,57 @@
 #!/bin/bash
 
+source "common.sh"
+
 # generate /must-gather/version file
-. version
 echo "opendatahub/must-gather" > /must-gather/version
 version >> /must-gather/version
 
+# define default namespaces
 OPERATOR_NS=${OPERATOR_NAMESPACE:-redhat-ods-operator}
 NOTEBOOKS_NS=${NOTEBOOK_NAMESPACE:-rhods-notebooks}
 MONITORING_NS=${MONITORING_NAMESPACE:-redhat-ods-monitoring}
 APPLICATIONS_NS=${APPLICATIONS_NAMESPACE:-redhat-ods-applications}
 
-oc adm inspect namespace/$OPERATOR_NS --dest-dir=must-gather || echo "Error getting logs from ${OPERATOR_NS}"
-oc adm inspect namespace/$NOTEBOOKS_NS --dest-dir=must-gather || echo "Error getting logs from ${NOTEBOOKS_NS}"
-oc adm inspect namespace/$MONITORING_NS --dest-dir=must-gather  || echo "Error getting logs from ${MONITORING_NS}"
-oc adm inspect namespace/$APPLICATIONS_NS --dest-dir=must-gather  || echo "Error getting logs from ${APPLICATIONS_NS}"
+oc adm inspect namespace/$OPERATOR_NS --dest-dir="$DST_DIR" || echo "Error getting logs from ${OPERATOR_NS}"
+oc adm inspect namespace/$NOTEBOOKS_NS --dest-dir="$DST_DIR" || echo "Error getting logs from ${NOTEBOOKS_NS}"
+oc adm inspect namespace/$MONITORING_NS --dest-dir="$DST_DIR"  || echo "Error getting logs from ${MONITORING_NS}"
+oc adm inspect namespace/$APPLICATIONS_NS --dest-dir="$DST_DIR"  || echo "Error getting logs from ${APPLICATIONS_NS}"
 
-/usr/bin/gather_data_science_pipelines
-/usr/bin/gather_model_mesh
-/usr/bin/gather_notebooks
+# set component or default to all
+component=${COMPONENT:-all}
+case "$component" in
+    "dsp")
+        /usr/bin/gather_data_science_pipelines
+        ;;
+    "modelmesh")
+        /usr/bin/gather_serving
+        ;;
+    "ksever")
+        /usr/bin/gather_serving
+        ;;
+    "dashboard")
+        echo "It has been included in the default namespace."
+        ;;
+    "workbench")
+        /usr/bin/gather_notebooks
+        ;;
+    "dw")
+        /usr/bin/gather_codeflare
+        /usr/bin/gather_kuberay
+        /usr/bin/gather_kueue
+        ;;
+    "mr"
+        echo "TBD."
+        ;;
+    *) # for all 
+        /usr/bin/gather_data_science_pipelines
+        /usr/bin/gather_serving
+        /usr/bin/gather_notebooks
+        /usr/bin/gather_codeflare
+        /usr/bin/gather_kuberay
+        /usr/bin/gather_kueue
+        ;;
+esac
+
 # force disk flush to ensure that all data gathered is accessible in the copy container
 sync
-
-
